[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install -g pnpm@9",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "pnpm exec tsc"
]

[start]
cmd = "node apps/api/dist/index.js"
